# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateTimeField()),
                ('note_name', models.CharField(max_length=200)),
                ('note_text', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'db_table': 'note',
            },
        ),
    ]
