# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
