# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_date',
            field=models.DateTimeField(null=True),
        ),
    ]
